version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
